# Nginx Dockerfile for Development
FROM nginx

# Copy our custom configuration
COPY ./default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
